version: 3

tasks:
  lsp:js:build:
    desc: Build the LSP
    dir: js/lsp
    cmds:
      - yarn build

  ide:vscode:dev:
    desc: Build everything and install the extension
    cmds:
      - task: lsp:js:build
      - task: ide:vscode:clean
      - task: ide:vscode:package
      - task: ide:vscode:install

  ide:vscode:clean:
    desc: Clean VS Code extension build artifacts and run Yarn
    dir: ide/vscode
    cmds:
      - rm -rf node_modules
      - rm -rf dist
      - yarn
  ide:vscode:package:
    desc: Package the VS Code extension
    dir: ide/vscode
    cmds:
      - vsce package
  ide:vscode:install:
    desc: Install the VS Code extension
    dir: ide/vscode
    cmds:
      - code --install-extension rhai-*.vsix --force
