[package]
name = "rhai-lsp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
tracing = "0.1.28"
lsp-async-stub = "0.2.0"
rhai-rowan = { path = "../rowan" }
lsp-types = "0.90.0"
once_cell = "1.8.0"
futures = "0.3.17"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1", features = ["rt-multi-thread"] }
clap = { version = "3.0.0-beta.2", optional = true }
ctrlc = { version = "3", optional = true }
notify = { version = "4", optional = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = { version = "0.2", features = [
    "serde-serialize",
] }
wasm-bindgen-futures = { version = "0.4" }
console_error_panic_hook = { version = "0.1" }
js-sys = { version = "0.3" }
tracing-wasm = { version = "0.2.0" }
serde_json = "1.0.68"

[features]
default = []
cli = ["clap", "ctrlc", "notify"]
wasm-export = []
