[package]
name = "rhai-sourcegen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.1"
proc-macro2 = "1.0.29"
quote = "1.0.9"
ungrammar = "1.14.4"
xshell = "0.1.17"
