[package]
name = "rhai-sourcegen"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prettyplease = "0.1.12"
proc-macro2 = "1.0.29"
quote = "1.0.9"
syn = "1.0.96"
ungrammar = "1.14.4"
